### PR TITLE
make long/double fn settable

### PR DESCRIPTION
**Pull request by 2e0byo**
This is literally the same as

https://github.com/peterhinch/micropython-async/pull/47

Except for the v3 branch.

### CODE REVIEW

**Review by peterhinch — CHANGES_REQUESTED** [review]
The aim of this change looks good.

I think 55 should read
```python
self._ld = False
```
(The state of ._ld is tested in the code.)

I would suggest writing the methods thus:
```python
    def long_func(self, func=False, args=()):
        self._lf = func
        self._la = args
        self._ld = Delay_ms(func, args) if func else False
```
This is more compact, avoids needless references to **self**, and provides a default where calling the method without args clears down the callback.

**Comment by peterhinch** [comment]
I think there is a problem if the long or double functions are swapped out while the respective timer is running. We need to stop any running `Delay_ms` instance before installing a new one.

**Comment by 2e0byo** [comment]
gah, 4 line PR and it had a silly bug in it.

How's this?  I'm not familiar with `Delay_ms()` so I'm only guessing `.stop()` will work.

**Comment by peterhinch** [comment]
Now merged. I will update the docs.

**Comment by peterhinch** [comment]
**.stop** will work.

As it happens I am currently updating **Delay_ms** to use the new uasyncio **ThreadSafeFlag** and other improvements.

In the light of this PR I will include a **.callback** method which will enable the **Delay_ms** callback and args to be changed at runtime. This will have a knock-on effect on this change, as there will no longer be a need to stop the timer and instantiate a new one: it will be possible to assign the new long press function to the existing timer (even if it is running).

Thanks for this PR - it has encouraged me to consider changing callbacks at runtime, something I hadn't previously thought of.

**Comment by 2e0byo** [comment]
> In the light of this PR I will include a **.callback** method which will enable the **Delay_ms** callback and args to be changed at runtime. <snip>

That's likely pretty useful actually: I currently just roll my own poll-and-trigger loop whenever I need a delayed fn because I always seem to need to change things down the line.  (But that might be because I only really tinker with replacing clapped-out controllers in domestic hardware).  Buttons for me always have state; previous I've just used a dummy fn and updated that to point at the right action.

Very useful libraries btw!

**Comment by peterhinch** [comment]
I have pushed an update. You might be interested in `primitives/tests/switches.py` which has a new test. The callback for long press changes all the other callbacks and then pulls the rug from under its own feet by changing itself.

It was for fear of this kind of thing that I imposed the old restriction of asking users to set callbacks before starting the scheduler. However with the change to `Delay_ms` I think we have a solution.

If you find any problems please raise a new issue.

**Pull request merged**
