### PR TITLE
Correct formatting issues in TUTORIAL.md

### PR DESCRIPTION
**Pull request by craftyguy**
- Fixed links back to TOC at the end of each section

- Fixed indention issues in TOC itself, had to resort to using a bulleted list to get more than 1 level of indentation. There might be a better way to do this, but I sure could not find it!

### CODE REVIEW

**Comment by peterhinch** [comment]
Alas not all of your 'jump to contents' links work, e.g. the one in section 2.1. I experienced the same issue when I experimented with removing the ###### strings. I think your original syntax hit on a workround for a bug in the markdown rendering. So I've reverted that change. If you find a way to make these links look nice and work reliably I'd love to see it.

**Comment by craftyguy** [comment]
Weird, I'm not seeing any broken 'jump to content' links in the version that I created this PR from: https://github.com/craftyguy/micropython-async/blob/master/TUTORIAL.md

For example, the link under 2.1 takes me back to the TOC. In fact, all of the 'jump to contents' links are all the same in this PR, so maybe there's some browser-specific shenanigans at play here? I have been using a browser based on chromium, if that means anything. Anyways, sorry for all this PR thrash, I promise I'm just trying to help :)

**Comment by peterhinch** [comment]
I'm grateful for your help, and I've now been able to add TOC's to some of my other docs thanks to your insights. I'm happy with the version I now have, which achieves a reasonable TOC layout. I don't know why I get erratic results when I put a space between the ###### string and the link; as you say it may be browser related. Unless anyone reports problems I plan to stick with what we've achieved.

Thanks again for your assistance, it really is much appreciated.

**Comment by peterhinch** [comment]
This is just FYI. Out of sheer curiosity I spent some more time on this.

I'd incorrectly diagnosed the problem. The issue with the "jump to contents" links is unrelated to their precise formatting, so I'm using your format. It is browser independent and I think it's a bug in the GitHub markdown processing. Doubtless there's a workround but I haven't found it. 

To replicate, go to the tutorial TOC and jump to section 2.2 then use the link at the end to jump back to the TOC. Now **scroll** down to section 3.1. The jump to TOC link at the end of that section doesn't work.

I've tested this in Firefox and Chromium. Oddly links to other documents work fine. If you can be bothered and happen to find a workround do let me know :+1:

**Comment by craftyguy** [comment]
Wow, yea, I see what you mean. Just reproduced it on Firefox for Android. I'll see if I can figure out what is going on, or at least where one might report potential github markdown bugs to github!

**Comment by peterhinch** [comment]
I think what may be going on is this. When you jump back to the TOC, then scroll somewhere else, it "thinks" it's still located at the TOC so the jump has no effect. This explains why jumps to other docs work. Alas as a theory it doesn't offer any obvious workrounds.

**Pull request closed without merging**
