### PR TITLE
Tutorial v3 lock import change

### PR DESCRIPTION
**Pull request by ThinkTransit**
Hi Peter,

Very minor change to the import of the Lock primitive.

I think it needs to be imported like this?

```python
from uasyncio.lock import Lock
```

### CODE REVIEW

**Review by peterhinch — COMMENTED** [review]
This PR is incorrect. `uasyncio` uses a [lazy loader](https://github.com/micropython/micropython/blob/1093dea70924a785543326773319dbb156e05c15/extmod/uasyncio/__init__.py#L14) which enables the code in the tutorial to work:
```py
Connected to MicroPython at /dev/ttyACM0
Use Ctrl-] to exit this shell

>>> from uasyncio import Lock
>>> 
```

**Comment by ThinkTransit** [comment]
Ok thanks Peter, have you tested on 1.20? I'm building myself so possibly I have missed something.

```python
MicroPython v1.20.0-52-g9a5969d71-dirty on 2023-05-07; INSIGHT_V1 with ESP32-S2
Type "help()" for more information.
>>> 
>>> from uasyncio import Lock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'uasyncio.Lock'
>>> 
```

**Comment by peterhinch** [comment]
Yes, I am running V1.20. Check that your build includes `/extmod/uasyncio/__init__.py`. You might like to run a pre-built firmware to verify that it is a build issue.

**Comment by ThinkTransit** [comment]
I pulled the latest code from github and rebuilt the firmware, problem doesn't exist anymore, not sure where the gremlin was! Thanks for putting the tutorial together it's a great resource.

**Pull request closed without merging**
